version: '3.9'
services:
  ubuntu:
    entrypoint: ['bash']
    tty: true
    build:
      context: ./
      dockerfile: ./pytube_builders/ubuntu/Dockerfile
  windows:
    tty: true
    build:
      context: ./
      dockerfile: ./pytube_builders/windows/Dockerfile