version: 2.1
orbs:
  win: circleci/windows@2.4.1
jobs:
  lin-build:
    docker:
      - image: cimg/python:3.10.2
    resource_class: medium
    steps:
      - checkout:
          path: ~/project
      - run: mkdir -p ~/project/artifacts
      - run: poetry install
      - run: poetry run task build
      - run: poetry run task format
      - run: mv dist/Pytube-TKGUI artifacts/Pytube-TKGUI_linux
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/project/artifacts
          # Must be relative path from root
          paths:
            - "Pytube-TKGUI_linux"
  win-build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ./artifacts
      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - run: choco install python --version=3.8.10
      - run: (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
      - run:
            name: "Poetry install" 
            command: "%APPDATA%\\Python\\Scripts\\poetry install"
            shell: cmd.exe
      - run:
            name: "Poetry format" 
            command: "%APPDATA%\\Python\\Scripts\\poetry run task format"
            shell: cmd.exe
      - run:
            name: "Poetry build" 
            command: "%APPDATA%\\Python\\Scripts\\poetry run task build"
            shell: cmd.exe
      - run:
          name: "Copy executable to artifacts"
          command: mv dist/Pytube-TKGUI.exe artifacts/Pytube-TKGUI_windows.exe
          shell: bash.exe
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: artifacts
          # Must be relative path from root
          paths:
            - "Pytube-TKGUI_windows.exe"
  pgr:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(./artifacts/Pytube-TKGUI_linux --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
      
workflows:
  version: 2
  build:
    jobs:
      - win-build:
          name: Windows
      - lin-build:
          name: Linux
          requires: [Windows]
      - pgr:
          name: "Push Github Release"
          requires: [Linux]
          filters:
            branches:
              only:
                - main
            tags:
              only: /^\d+\.\d+\.\d+$/