version: 2.1
orbs:
  win: circleci/windows@2.4.1
jobs:
  lin-build:
    docker:
      - image: cimg/python:3.10.2
    resource_class: medium
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ./artifacts
      - run: poetry install
      - run: poetry run task build
      - run: mv dist/Pytube-TKGUI artifacts/Pytube-TKGUI_linux
      - store_artifacts:
          path: artifacts/
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/project/artifacts
          # Must be relative path from root
          paths:
            - "Pytube-TKGUI_linux"
            - "Pytube-TKGUI_windows.exe"
  win-build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout:
          path: ~/project
      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - run: choco install python --version=3.8.10
      - run: (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
      - run:
            name: "Poetry install" 
            command: "%APPDATA%\\Python\\Scripts\\poetry install"
            shell: cmd.exe
      - run:
            name: "Poetry build" 
            command: "%APPDATA%\\Python\\Scripts\\poetry run task build"
            shell: cmd.exe
      - run:
          name: "Create artifacts"
          command: mkdir artifacts
          shell: bash.exe
      - run:
          name: "Copy executable to artifacts"
          command: mv dist/Pytube-TKGUI.exe artifacts/Pytube-TKGUI_windows.exe
          shell: bash.exe
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: artifacts
          # Must be relative path from root
          paths:
            - "Pytube-TKGUI_windows.exe"
  pgr:
    docker:
      - image: circleci/golang:1.8
    resource_class: medium
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: ls -al artifacts
      - run: chmod +x artifacts/Pytube-TKGUI_linux
      - run: artifacts/Pytube-TKGUI_linux --version
      - run: ldd artifacts/Pytube-TKGUI_linux
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION="$(artifacts/Pytube-TKGUI_linux --version)"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
      
workflows:
  version: 2
  build:
    jobs:
      - win-build:
          name: Windows
      - lin-build:
          name: Linux
          requires: [Windows]
#      - pgr:
#          name: "Push Github Release"
#          requires: [Linux]
#          filters:
#            branches:
#              only:
#                - main
#            tags:
#              only: /^\d+\.\d+\.\d+$/