version: 2.1
orbs:
  win: circleci/windows@2.4.1
jobs:
  lin-build:
    docker:
      - image: cimg/python:3.10.2
    resource_class: medium
    steps:
      - checkout:
          path: ~/project
      - run: mkdir -p ~/project/artifacts
      - run: poetry install
      - run: poetry run task build
      - run: ls -al
      - run: ls -al dist
      - run: mv dist/* artifacts/
      - store_artifacts:
          path: artifacts/
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/project/artifacts
          # Must be relative path from root
          paths:
            - "*"
  win-build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - run: choco install python --version=3.8.10
      - run: (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
      - run:
            name: "Poetry install" 
            command: "%APPDATA%\\Python\\Scripts\\poetry install"
            shell: cmd.exe
      - run:
            name: "Poetry build" 
            command: "%APPDATA%\\Python\\Scripts\\poetry run task build"
            shell: cmd.exe
      - run: dir dist
      - run:
          name: "Copy executable to artifacts"
          command: mv dist/* artifacts/
          shell: bash.exe
      - run: dir artifacts
      - store_artifacts:
          path: artifacts/
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: artifacts
          # Must be relative path from root
          paths:
            - "*.exe"
  pgr:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
      
workflows:
  version: 2
  build:
    jobs:
      - win-build:
          name: windows
      - lin-build:
          name: linux
          requires: [windows]