version: 2.1
jobs:
  win-build:
    docker:
      - image: cimg/windows@2.2.0
    steps:
      - checkout
      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - run: mkdir -p artifacts
      - run: echo "Trying out workspaces" > artifacts/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: artifacts
          # Must be relative path from root
          paths:
            - echo-output
  lin-build:
    docker:
      - image: cimg/python:3.8
    steps:
      - attach_workspace:
            at: ./artifacts
      - checkout
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - run: poetry install
      - run: poetry run task build
  pgr:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
      
workflows:
  version: 2
  one:
    jobs:
      - win-build
  two:
    jobs:
      - lin-build